// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3pVM8AC4cxrrsFXLfGMDKMa49bQYYlaE',
    appId: '1:697199258846:web:7144515864ef6772eba64f',
    messagingSenderId: '697199258846',
    projectId: 'intern-globe',
    authDomain: 'intern-globe.firebaseapp.com',
    databaseURL: 'https://intern-globe-default-rtdb.firebaseio.com',
    storageBucket: 'intern-globe.firebasestorage.app',
    measurementId: 'G-7CWG1NPJBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2PTP9G41rtq_SunlKU3eYDuCxGvPEcTQ',
    appId: '1:697199258846:android:96e74a6d634805b5eba64f',
    messagingSenderId: '697199258846',
    projectId: 'intern-globe',
    databaseURL: 'https://intern-globe-default-rtdb.firebaseio.com',
    storageBucket: 'intern-globe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz6o9_VR4Elw5m8YZ4uet_ZrjDImLcvQ0',
    appId: '1:697199258846:ios:edc9f9d9b72e91d2eba64f',
    messagingSenderId: '697199258846',
    projectId: 'intern-globe',
    databaseURL: 'https://intern-globe-default-rtdb.firebaseio.com',
    storageBucket: 'intern-globe.firebasestorage.app',
    androidClientId: '697199258846-2f95v9l8qsdvfulian27d23580ql3cdq.apps.googleusercontent.com',
    iosClientId: '697199258846-belh0s4vhm6000e3r5sfpmcpc3jfj166.apps.googleusercontent.com',
    iosBundleId: 'com.example.internglobe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz6o9_VR4Elw5m8YZ4uet_ZrjDImLcvQ0',
    appId: '1:697199258846:ios:edc9f9d9b72e91d2eba64f',
    messagingSenderId: '697199258846',
    projectId: 'intern-globe',
    databaseURL: 'https://intern-globe-default-rtdb.firebaseio.com',
    storageBucket: 'intern-globe.firebasestorage.app',
    androidClientId: '697199258846-2f95v9l8qsdvfulian27d23580ql3cdq.apps.googleusercontent.com',
    iosClientId: '697199258846-belh0s4vhm6000e3r5sfpmcpc3jfj166.apps.googleusercontent.com',
    iosBundleId: 'com.example.internglobe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3pVM8AC4cxrrsFXLfGMDKMa49bQYYlaE',
    appId: '1:697199258846:web:e896ace48c5233b1eba64f',
    messagingSenderId: '697199258846',
    projectId: 'intern-globe',
    authDomain: 'intern-globe.firebaseapp.com',
    databaseURL: 'https://intern-globe-default-rtdb.firebaseio.com',
    storageBucket: 'intern-globe.firebasestorage.app',
    measurementId: 'G-794RR0RENK',
  );
}
